basePath: /
definitions:
  types.APIError:
    properties:
      code:
        type: string
      details:
        type: string
      message:
        type: string
    type: object
  types.APIResponse:
    properties:
      data: {}
      error:
        $ref: '#/definitions/types.APIError'
      success:
        type: boolean
    type: object
  types.AssetInfo:
    properties:
      balance:
        type: string
      balance_wei:
        type: string
      change_24h:
        type: number
      contract_address:
        type: string
      is_native:
        type: boolean
      last_updated:
        type: string
      token_name:
        type: string
      token_price:
        type: number
      token_symbol:
        type: string
      usd_value:
        type: number
    type: object
  types.AssetQueryRequest:
    properties:
      chain_id:
        type: integer
      force_refresh:
        type: boolean
      wallet_address:
        type: string
    required:
    - chain_id
    - wallet_address
    type: object
  types.ChainAssetInfo:
    properties:
      assets:
        items:
          $ref: '#/definitions/types.AssetInfo'
        type: array
      chain_id:
        type: integer
      chain_name:
        type: string
      chain_symbol:
        type: string
      last_updated:
        type: string
      total_usd_value:
        type: number
    type: object
  types.JSONB:
    additionalProperties: true
    type: object
  types.RefreshTokenRequest:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  types.SwitchChainRequest:
    properties:
      chain_id:
        type: integer
    required:
    - chain_id
    type: object
  types.SwitchChainResponse:
    properties:
      access_token:
        type: string
      expires_at:
        type: string
      message:
        type: string
      refresh_token:
        type: string
      user:
        $ref: '#/definitions/types.User'
    type: object
  types.User:
    properties:
      chain_id:
        type: integer
      created_at:
        type: string
      id:
        type: integer
      last_login:
        type: string
      preferences:
        $ref: '#/definitions/types.JSONB'
      status:
        type: integer
      updated_at:
        type: string
      wallet_address:
        type: string
    type: object
  types.UserAssetResponse:
    properties:
      last_updated:
        type: string
      other_chains:
        description: 为空
        items:
          $ref: '#/definitions/types.ChainAssetInfo'
        type: array
      primary_chain:
        $ref: '#/definitions/types.ChainAssetInfo'
      primary_chain_id:
        type: integer
      total_usd_value:
        type: number
      wallet_address:
        type: string
    type: object
  types.UserProfile:
    properties:
      chain_id:
        type: integer
      created_at:
        type: string
      last_login:
        type: string
      preferences:
        $ref: '#/definitions/types.JSONB'
      wallet_address:
        type: string
    type: object
  types.WalletConnectRequest:
    properties:
      chain_id:
        type: integer
      message:
        type: string
      signature:
        type: string
      wallet_address:
        type: string
    required:
    - chain_id
    - message
    - signature
    - wallet_address
    type: object
  types.WalletConnectResponse:
    properties:
      access_token:
        type: string
      expires_at:
        type: string
      refresh_token:
        type: string
      user:
        $ref: '#/definitions/types.User'
    type: object
host: localhost:8080
info:
  contact: {}
  description: TimeLocker Backend API
  title: TimeLocker Backend API
  version: "1.0"
paths:
  /api/v1/assets:
    get:
      consumes:
      - application/json
      description: 获取用户在所有链上的资产信息
      parameters:
      - description: 主要显示的链ID
        in: query
        name: chain_id
        type: integer
      - description: 是否强制刷新
        in: query
        name: force_refresh
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/types.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/types.UserAssetResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/types.APIResponse'
            - properties:
                error:
                  $ref: '#/definitions/types.APIError'
              type: object
        "401":
          description: Unauthorized
          schema:
            allOf:
            - $ref: '#/definitions/types.APIResponse'
            - properties:
                error:
                  $ref: '#/definitions/types.APIError'
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/types.APIResponse'
            - properties:
                error:
                  $ref: '#/definitions/types.APIError'
              type: object
      security:
      - BearerAuth: []
      summary: 获取用户资产
      tags:
      - 资产
  /api/v1/assets/refresh:
    post:
      consumes:
      - application/json
      description: 强制刷新用户在指定链上的资产信息
      parameters:
      - description: 刷新请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/types.AssetQueryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/types.APIResponse'
            - properties:
                data:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/types.APIResponse'
            - properties:
                error:
                  $ref: '#/definitions/types.APIError'
              type: object
        "401":
          description: Unauthorized
          schema:
            allOf:
            - $ref: '#/definitions/types.APIResponse'
            - properties:
                error:
                  $ref: '#/definitions/types.APIError'
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/types.APIResponse'
            - properties:
                error:
                  $ref: '#/definitions/types.APIError'
              type: object
      security:
      - BearerAuth: []
      summary: 刷新用户资产
      tags:
      - 资产
  /api/v1/auth/profile:
    get:
      consumes:
      - application/json
      description: 获取当前认证用户的资料信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/types.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/types.UserProfile'
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/types.APIResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/types.APIResponse'
      security:
      - BearerAuth: []
      summary: 获取用户资料
      tags:
      - 认证
  /api/v1/auth/refresh:
    post:
      consumes:
      - application/json
      description: 使用刷新令牌获取新的访问令牌
      parameters:
      - description: 刷新令牌请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/types.RefreshTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/types.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/types.WalletConnectResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.APIResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/types.APIResponse'
      summary: 刷新访问令牌
      tags:
      - 认证
  /api/v1/auth/switch-chain:
    post:
      consumes:
      - application/json
      description: 切换到新的区块链
      parameters:
      - description: 切换链请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/types.SwitchChainRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/types.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/types.SwitchChainResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.APIResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/types.APIResponse'
      security:
      - BearerAuth: []
      summary: 切换链
      tags:
      - 认证
  /api/v1/auth/wallet-connect:
    post:
      consumes:
      - application/json
      description: 通过钱包签名进行用户认证
      parameters:
      - description: 钱包连接请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/types.WalletConnectRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/types.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/types.WalletConnectResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.APIResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/types.APIResponse'
      summary: 钱包连接认证
      tags:
      - 认证
  /health:
    get:
      consumes:
      - application/json
      description: 检查服务健康状态
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 健康检查
      tags:
      - 系统
schemes:
- http
- https
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
