server:
  port: "8080"
  mode: "debug"  # debug, release, test

database:
  host: "localhost"
  port: 5432
  user: "timelocker"
  password: "timelocker"
  dbname: "timelocker_db"
  sslmode: "disable"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

jwt:
  secret: "timelocker-jwt-secret-v1"
  access_expiry: "24h"   # 24小时
  refresh_expiry: "168h" # 7天

# Covalent API配置
covalent:
  api_key: "xxx"  # 请设置你的Covalent API Key
  base_url: "https://api.covalenthq.com/v1"
  request_timeout: "30s"
  cache_prefix: "asset:"
  cache_expiry: 300  # 缓存过期时间，单位秒（5分钟）

# RPC配置 - 用于监听链上事件
rpc:
  # RPC提供商配置（用户只需要填写API key）
  alchemy_api_key: "xxx"
  infura_api_key: "xxx"
  
  # 当前使用的提供商（alchemy、infura 或 custom）
  # alchemy: 使用Alchemy RPC
  # infura: 使用Infura RPC  
  # custom: 使用自定义RPC（公共节点）
  provider: "alchemy"
  
  # 监听配置
  poll_interval: "30s"  # 轮询间隔
  block_confirmations: 12  # 区块确认数
  max_block_range: 500  # 单次RPC请求的最大区块范围（alchemy限制为500）
  
  # 是否包含测试网
  include_testnets: true

# 邮件服务配置
email:
  smtp_host: "smtp.zoho.com"
  smtp_port: 587
  smtp_username: "zem@timelock.live"  # 发送邮件的邮箱地址
  smtp_password: "xxx"     # 邮箱应用密码（不是登录密码）
  from_name: "TimeLocker Notification"   # 发件人名称
  from_email: "zem@timelock.live"     # 发件人邮箱（通常与smtp_username相同）
  
  # 邮件通知功能配置
  verification_code_expiry: "10m"        # 验证码过期时间
  enable_emergency_mode: true            # 是否启用应急模式
  emergency_resend_interval: "2h"        # 应急邮件重发间隔
  emergency_max_attempts: 10             # 应急邮件最大发送次数
  
  # 邮件模板配置
  base_url: "http://16.163.43.186:8080"      # 前端基础URL，用于生成邮件中的链接 